@extends('layouts.seller')
@section('page_title', 'Sales reports')
@section('content')
<div class="page-heading"><div><div class="eyebrow">BUSINESS INSIGHTS</div><h1>Sales reports</h1><p class="subtitle">Paid, delivered orders with the commission recorded at checkout.</p></div><a class="button secondary" href="{{ route('seller.reports',['from_date'=>$from,'to_date'=>$to,'export'=>'csv']) }}">↓ Export CSV</a></div>
<form class="filters" method="GET"><label>From<input type="date" name="from_date" value="{{ $from }}" required></label><label>To<input type="date" name="to_date" value="{{ $to }}" required></label><button class="button" type="submit">Update report</button></form>
<div class="metrics">@foreach(['Gross sales'=>$summary['gross'],'Commission'=>$summary['commission'],'Net sales'=>$summary['gross']-$summary['commission']] as $label=>$value)<div class="metric"><div class="metric-top">{{ $label }}</div><div class="metric-value">₱{{ number_format($value/100,2) }}</div></div>@endforeach<div class="metric"><div class="metric-top">Paid & delivered orders</div><div class="metric-value">{{ $summary['count'] }}</div></div></div>
<p class="subtitle" style="margin-bottom:20px">Net sales exclude shipping and are not a withdrawable wallet balance. Pending, cancelled and refunded payments are excluded.</p>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Order</th><th>Delivery date</th><th>Gross sales</th><th>Commission</th><th>Net sales</th></tr></thead><tbody>@forelse($orders as $order)<tr><td>{{ $order->order->reference }}</td><td>{{ $order->delivered_at?->format('M j, Y') }}</td><td class="amount">₱{{ number_format($order->subtotal_minor/100,2) }}</td><td class="amount">₱{{ number_format($order->commission_minor/100,2) }}</td><td class="amount">₱{{ number_format(($order->subtotal_minor-$order->commission_minor)/100,2) }}</td></tr>@empty<tr><td colspan="5"><div class="empty"><h3>No sales in this period</h3><p>Try a different date range. Paid orders appear here once delivered.</p></div></td></tr>@endforelse</tbody></table></div>@include('seller.partials.pagination',['paginator'=>$orders])</section>
@endsection
